<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <title> Asinhrono prigramiranje </title>
</head>
<body>
    <h3> Promise i izuzeci prilikom odbacivanja </h3>
    <script type="text/javascript">

        const promise = new Promise(function(resolve, reject){
            // simuliramo da li je uspesno obradjen taj neki zahtev ili ne
            const isSuccesful = Math.random() < 0.3;

            if(isSuccesful){
                resolve("Obecanje je ispunjeno");
            } else{
                reject("Obecanje nije ispunjeno");
            }
        });


        // NOTE: ako samo ovako napisemo, ako se desi da se pozove reject(), dobicemo ispis u konzoli u browseru:
        // `Uncaught (in promise) Obecanje nije ispunjeno!`
        // a ovaj then kako smo ga napisali se nece izvrsiti
        promise
            .then(function(value){
                document.body.appendChild(document.createTextNode(value));
            })
            // zbog toga dodajemo i ovaj catch deo. Ovo je deo koji ce se izvrsiti ako obecanje nije ispunjeno
            // tj samo u slucaju kada se pozove reject. Catch deo isto treba da primi funkciju sa jednim parametrom kao i then
            .catch(function(reason){
                document.body.appendChild(document.createTextNode(reason));
            });

    </script>
</body>
</html>