<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <title> Asinhrono prigramiranje </title>
</head>
<body>
    <h3> Promise i obrada izuzetaka </h3>
    <script type="text/javascript">

        const promise = new Promise(function(resolve, reject){
            // samo ispaljujemo gresku za priemr
            throw new Error("Doslo je do greske");
        });


        // u normalnim situacijama greske hvatamo sa try/catch, ali kada koristimo promise, to ne moze zato sto
        // try/catch hvata samo "sinhrone izuzetke", a promise se izvrsava asinhrono
            // try{
            //     promise.then(function(value){
            //         document.body.appendChild(document.createTextNode(value));
            //     });
            // } catch(err){
            //     document.body.appendChild(document.createTextNode(err));
            // }


        // .catch za nas moze da uhvati ove errore tako da to treba da koristimo
        promise
            .then(function(value){
                document.body.appendChild(document.createTextNode(value));
            })
            .catch(function(reason){
                document.body.appendChild(document.createTextNode(reason));
            });

    </script>
</body>
</html>